AWSTemplateFormatVersion: 2010-09-09
Description: ---
Metadata: 

Parameters: 

Mappings: 

Conditions: 

Resources: 
  iamRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal: 
              Service : 
              - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      MaxSessionDuration: 3600
    #Policies:
      #- 
       #PolicyName: "root"
       #PolicyDocument:
         #Version: "2012-10-17"
         #Statement:
            #- 
              #Effect: "Allow"
              #Action: "*"
              #Resource: "*"
Outputs: